# Model and hyperparameter configuration for classifier training
# Each model entry contains the class name and its hyperparameter search space for hyperopt

models:
  - name: RandomForestClassifier
    module: sklearn.ensemble
    params:
      n_estimators:
        type: int
        low: 50
        high: 300
      min_samples_split:
        type: int
        low: 2
        high: 10
      min_samples_leaf:
        type: int
        low: 1
        high: 5
  - name: XGBClassifier
    module: xgboost
    params:
      n_estimators:
        type: int
        low: 50
        high: 300
      max_depth:
        type: int
        low: 3
        high: 20
      learning_rate:
        type: float
        low: 0.01
        high: 0.3
      subsample:
        type: float
        low: 0.5
        high: 1.0
  # - name: LGBMClassifier
  #   module: lightgbm
  #   params:
  #     n_estimators:
  #       type: int
  #       low: 50
  #       high: 300
  #     max_depth:
  #       type: int
  #       low: 3
  #       high: 20
  #     learning_rate:
  #       type: float
  #       low: 0.01
  #       high: 0.3
  #     subsample:
  #       type: float
  #       low: 0.5
  #       high: 1.0
  - name: LogisticRegression
    module: sklearn.linear_model
    params:
      C:
        type: float
        low: 0.01
        high: 10.0
      penalty:
        type: categorical
        choices: ["l2"]
      solver:
        type: categorical
        choices: ["lbfgs"] 
      max_iter:
        type: categorical
        choices: [1000]
  - name: AdaBoostClassifier
    module: sklearn.ensemble
    params:
      n_estimators:
        type: int
        low: 50
        high: 300
      learning_rate:
        type: float
        low: 0.01
        high: 2.0